import { InfoPage, InfoSection } from '@/components/Shared/InfoPage';

export const metadata = {
  title: 'Terms of Service — Intelliquery',
  description: 'The terms that govern your use of Intelliquery.',
};

export default function TermsPage() {
  return (
    <InfoPage title="Terms of Service" subtitle="Last updated: July 2, 2026">
      <InfoSection title="1. Acceptance of terms">
        <p>
          By creating an account or using Intelliquery (the &ldquo;Service&rdquo;), you agree to be
          bound by these Terms of Service. If you are using the Service on behalf of an
          organization, you represent that you have authority to bind that organization to these
          terms.
        </p>
      </InfoSection>

      <InfoSection title="2. The service">
        <p>
          Intelliquery translates natural-language questions into SQL queries, executes them
          against databases you connect, and presents results and AI-generated analysis. Query
          execution is read-only: the Service only issues <code>SELECT</code> statements against
          your databases.
        </p>
      </InfoSection>

      <InfoSection title="3. Your responsibilities">
        <ul className="list-disc pl-5 space-y-2">
          <li>You must only connect databases you are authorized to access.</li>
          <li>You are responsible for the credentials you provide and for scoping them appropriately — we recommend a read-only database user.</li>
          <li>You must keep your account password confidential and notify us of any suspected unauthorized use.</li>
          <li>You must not attempt to circumvent the Service&rsquo;s safety controls, probe its infrastructure, or use it to violate any law.</li>
        </ul>
      </InfoSection>

      <InfoSection title="4. AI-generated content">
        <p>
          SQL queries, summaries, and insights are generated by AI and may contain errors. Review
          generated queries and results before relying on them for business, financial, or legal
          decisions. The Service is provided for analytical assistance, not as a system of record.
        </p>
      </InfoSection>

      <InfoSection title="5. Data and privacy">
        <p>
          Our handling of your data is described in the Privacy Policy. In short: connection
          credentials are encrypted at rest, query execution is read-only, and you control which
          tables and columns are visible to the AI.
        </p>
      </InfoSection>

      <InfoSection title="6. Availability and changes">
        <p>
          The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We may
          modify, suspend, or discontinue features at any time. We will make reasonable efforts to
          notify you of material changes to these terms.
        </p>
      </InfoSection>

      <InfoSection title="7. Limitation of liability">
        <p>
          To the maximum extent permitted by law, Intelliquery shall not be liable for any
          indirect, incidental, special, or consequential damages, or for any loss of data,
          revenue, or profits arising from your use of the Service.
        </p>
      </InfoSection>

      <InfoSection title="8. Termination">
        <p>
          You may stop using the Service and delete your connections at any time. We may suspend
          or terminate accounts that violate these terms.
        </p>
      </InfoSection>

      <InfoSection title="9. Contact">
        <p>
          Questions about these terms? Contact us at{' '}
          <a href="mailto:support@intelliquery.ai" className="text-brand underline">
            support@intelliquery.ai
          </a>.
        </p>
      </InfoSection>
    </InfoPage>
  );
}
